### ISSUE TITLE
Issue using m3u-builder

### ISSUE THREAD

**Issue by wyild1** [grkblood13/m3u-builder#3]
Hi there! 

So i have had this working for a month or 2, then all of a sudden this error started coming up this morning.  Talked to buddy using same source and using m3u-builder and hes getting the same error.  I droped my params.cfg file to see if that was causing an issue and it didnt help.  I can wget the files from my provider....so im at a loss

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot call method 'forEach' of undefined
    at /Data/scripts/stuff/m3u-builder-master/m3u-builder.js:510:25
    at Parser.<anonymous> (/Data/scripts/stuff/m3u-builder-master/node_modules/xml2js/lib/xml2js.js:489:18)
    at Parser.emit (events.js:95:17)
    at Object.onclosetag (/Data/scripts/stuff/m3u-builder-master/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/Data/scripts/stuff/m3u-builder-master/node_modules/xml2js/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/Data/scripts/stuff/m3u-builder-master/node_modules/xml2js/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/Data/scripts/stuff/m3u-builder-master/node_modules/xml2js/node_modules/sax/lib/sax.js:905:7)
    at Object.write (/Data/scripts/stuff/m3u-builder-master/node_modules/xml2js/node_modules/sax/lib/sax.js:1452:13)
    at Parser.exports.Parser.Parser.parseString (/Data/scripts/stuff/m3u-builder-master/node_modules/xml2js/lib/xml2js.js:508:31)
    at Parser.parseString (/Data/scripts/stuff/m3u-builder-master/node_modules/xml2js/lib/xml2js.js:7:59)
    at /Data/scripts/stuff/m3u-builder-master/m3u-builder.js:493:11
```

**Comment by lselinger** [comment]
Seeing the exact same thing and only recently: 

<pre>
events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot call method 'forEach' of undefined
    at /usr/local/lib/node_modules/m3u-builder/m3u-builder.js:477:25
    at Parser.<anonymous> (/usr/local/lib/node_modules/m3u-builder/node_modules/xml2js/lib/xml2js.js:489:18)
    at Parser.EventEmitter.emit (events.js:95:17)
    at Object.onclosetag (/usr/local/lib/node_modules/m3u-builder/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/usr/local/lib/node_modules/m3u-builder/node_modules/xml2js/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/local/lib/node_modules/m3u-builder/node_modules/xml2js/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/local/lib/node_modules/m3u-builder/node_modules/xml2js/node_modules/sax/lib/sax.js:889:7)
    at Object.write (/usr/local/lib/node_modules/m3u-builder/node_modules/xml2js/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/m3u-builder/node_modules/xml2js/lib/xml2js.js:508:31)
    at Parser.parseString (/usr/local/lib/node_modules/m3u-builder/node_modules/xml2js/lib/xml2js.js:7:59)
    at /usr/local/lib/node_modules/m3u-builder/m3u-builder.js:460:11
</pre>

**Comment by wyild1** [comment]
OK well dont know what to say but its magically working again.  Weirddddddd haha

**Comment by grkblood13** [comment]
I'm going to close this then. If y'all have the same issue comment here and I'll get a notification.
